apps/frontend/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('imagefit/', include('imagefit.urls')),
    path('team/', views.MemberListView.as_view(), name='member_list'),
    path('kontakt/', views.ContactView.as_view(), name='contact'),
    path('impressum/', views.ImprintView.as_view(), name='imprint'),
    path('datenschutz/', views.DataProtectionView.as_view(), name='data_protection'),
    path('seminargruppen/', views.SeminarGroupListView.as_view(), name='seminargroup_list'),
    path('seminarthema/<slug:slug>/', views.SeminarTopicDetailView.as_view(), name='seminartopic_detail'),
    path('team/<slug:slug>/', views.MemberDetailView.as_view(), name='member_detail'),
    path('coaching/', views.CoachingView.as_view(), name='coaching')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import debug_toolbar
import config.admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('apps.frontend.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

apps/training/models.py
from apps.settings.models import Image
from apps.team.models import Member
from tinymce.models import HTMLField
from django.db import models


class SeminarGroup(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    description = models.TextField(verbose_name='Beschreibung', blank=True)
    slug = models.SlugField(verbose_name='Slug', unique=True,
                            help_text='Erscheint in der URL. Zum Beispiel: cocoo.de/seminargruppe/scrum/.')
    #
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    draft = models.BooleanField(default=True, verbose_name="Entwurf")

    class Meta:
        ordering = ['slug']
        verbose_name = 'Seminargruppe'
        verbose_name_plural = 'Seminargruppen'

    def __str__(self):
        return '{}'.format(self.name)

    def save(self, *args, **kwargs):
        self.slug = self.slug.lower()
        super().save(*args, **kwargs)

    @property
    def topics_sorted(self):
        return self.seminar_topics.order_by('-title')

    @staticmethod
    def all():
        return SeminarGroup.objects.filter(draft=False)


class SeminarTopic(models.Model):
    title = models.CharField(max_length=200, verbose_name='Name')
    slug = models.SlugField(verbose_name='Slug', unique=True,
                            help_text='Erscheint in der URL. Zum Beispiel: '
                                      'cocoo.de/seminarthema/certified-less-practitioner/.')
    short_description = models.TextField(verbose_name='Kurzbeschreibung')
    description = HTMLField(verbose_name='Beschreibung')
    image = models.ForeignKey(Image, verbose_name='Bild', blank=True, null=True, on_delete=models.PROTECT)
    certificate = models.TextField(verbose_name='Zertifikatsaussage')
    languages = models.TextField(verbose_name='Sprachen')
    executions = models.TextField(verbose_name='Durchführungen')
    seminar_group = models.ForeignKey(SeminarGroup, related_name='seminar_topics', verbose_name='Seminargruppe',
                                      on_delete=models.PROTECT)
    promotions = models.TextField(verbose_name='Rabattaktionen', blank=True)

    #
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    draft = models.BooleanField(default=True, verbose_name="Entwurf")

    class Meta:
        ordering = ['slug']
        verbose_name = 'Seminarthema'
        verbose_name_plural = 'Seminarthemen'

    def __str__(self):
        return '{}'.format(self.title)

    @staticmethod
    def all():
        return SeminarTopic.objects.filter(draft=False)


class SeminarExecution(models.Model):
    topic = models.ForeignKey(SeminarTopic, verbose_name='Thema', on_delete=models.CASCADE)
    start_date = models.DateField(verbose_name='Startdatum')
    end_date = models.DateField(verbose_name='Enddatum')
    location = models.CharField(max_length=50, verbose_name='Ort', blank=True)
    execution_choices = (
        ('PRESENCE', 'Präsenz'),
        ('VIRTUAL', 'Virtuell')
    )
    execution = models.CharField(choices=execution_choices, verbose_name='Durchführung', max_length=40)
    language = models.CharField(max_length=50, verbose_name='Sprache')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Preis', null=True, blank=True)
    early_booking_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Frühbucherpreis', null=True,
                                              blank=True)
    price_text = models.CharField(verbose_name='Text nach dem Preis', blank=True, max_length=100,
                                  help_text='Zum Beispiel: inkl. MwSt.')
    show_early_booking_price = models.BooleanField(verbose_name='Frühbucherpreis anzeigen')
    execution_hours = models.TextField(verbose_name='Durchführungszeiten')
    STATUS_CHOICES = (
        ('OPEN', 'Plätze verfügbar'),
        ('ALMOST_FULL', 'Wenige Plätze verfügbar'),
        ('FULL', 'Ausgebucht')
    )
    status = models.CharField(choices=STATUS_CHOICES, max_length=50, verbose_name='Buchungsstatus')
    members = models.ManyToManyField(Member, verbose_name='Teammitglieder', blank=True)
    show_on_index = models.BooleanField(verbose_name='Auf der Startseite im Slider anzeigen', default=True)
    #
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    draft = models.BooleanField(default=True, verbose_name="Entwurf")

    class Meta:
        ordering = ['start_date']
        verbose_name = 'Seminardurchführung'
        verbose_name_plural = 'Seminardurchführungen'

    def __str__(self):
        return '{} - {}: {}'.format(self.start_date.strftime('%d.%m.%Y'),
                                    self.end_date.strftime('%d.%m.%Y'), self.topic.title)

    @staticmethod
    def all():
        return SeminarExecution.objects.filter(draft=False)

apps/frontend/forms.py
from django import forms
from apps.training.models import SeminarExecution, SeminarTopic


class ContactForm(forms.Form):
    first_name = forms.CharField(label='Vorname', required=True)
    last_name = forms.CharField(label='Nachname', required=True)
    email = forms.EmailField(label='E-Mail', required=True)
    message = forms.CharField(label='Nachricht', widget=forms.Textarea, required=True)
    honey1234 = forms.CharField(label='Honeypot', widget=forms.HiddenInput(attrs={"autocomplete": "off"}), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].required:
                self.fields[field].label = self.fields[field].label + '*'

    def get_data(self):
        data = ''
        for field in self.fields:
            field_data = '{}: {}'.format(self.fields[field].label, self.cleaned_data[field])
            data = '{}\n{}'.format(data, field_data)
        return data

    def clean_honey1234(self):
        business = self.cleaned_data['honey1234']
        if business != '3948':
            raise forms.ValidationError('Leider ist da etwas schief gegangen. '
                                        'Bitte schreiben Sie uns eine E-Mail. Vielen Dank.')
        return business


class SeminarRegistrationForm(forms.Form):
    seminar = forms.ModelChoiceField(SeminarExecution.objects.exclude(status='FULL'), empty_label='Inhouse',
                                     required=False, label='Seminar')
    first_name = forms.CharField(label='Vorname', required=True)
    last_name = forms.CharField(label='Nachname', required=True)
    email = forms.EmailField(label='E-Mail', required=True)
    phone = forms.CharField(label='Telefon', required=True)
    amount_persons = forms.IntegerField(label='Anzahl Personen', required=True)
    honey1234 = forms.CharField(label='Honeypot', widget=forms.HiddenInput, required=True)
    topic = forms.ModelChoiceField(label='Seminarthema', widget=forms.HiddenInput, queryset=SeminarTopic.objects.all())
    message = forms.CharField(label='Nachricht', widget=forms.Textarea(attrs={'rows': 4, 'cols': 10}), required=False)

    def __init__(self, seminartopic=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if seminartopic:
            self.fields['topic'].initial = seminartopic
            self.fields['seminar'].queryset = self.fields['seminar'].queryset.filter(topic=seminartopic)
        for field in self.fields:
            if self.fields[field].required:
                self.fields[field].label = self.fields[field].label + '*'

    def get_data(self):
        data = ''
        for field in self.fields:
            field_data = '{}: {}'.format(self.fields[field].label, self.cleaned_data[field])
            data = '{}\n{}'.format(data, field_data)
        return data

    def clean_honey1234(self):
        business = self.cleaned_data['honey1234']
        if business != '3948':
            raise forms.ValidationError('Leider ist da etwas schief gegangen. '
                                        'Bitte schreiben Sie uns eine E-Mail. Vielen Dank.')
        return business

    def clean_seminar(self):
        seminar = self.cleaned_data['seminar']
        if seminar is None:
            return 'Inhouse'
        return seminar

apps/frontend/views.py
from django.contrib.auth.mixins import AccessMixin
from apps.training.models import SeminarGroup, SeminarExecution, SeminarTopic
from apps.settings.models import General
from apps.pages.models import Imprint, DataProtection, Contact, Team, Index, Seminars, Coaching, Seminar, \
    Member as MemberPage
from apps.customer.models import Testimonial
from apps.frontend.forms import ContactForm, SeminarRegistrationForm
from apps.team.models import Member, Book, Certification
from django.core.mail import send_mail
from django.db.models import Prefetch
from django.views import generic
from django.urls import reverse
from django.conf import settings


# mixins
class ProtectMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if settings.PROTECTED and not request.user.is_authenticated:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class AllContextMixin(generic.base.ContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['general'] = General.get_solo()
        context['seminar_groups'] = SeminarGroup.all()
        return context


# general views
class IndexView(ProtectMixin, AllContextMixin, generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seminar_groups'] = SeminarGroup.all()
        context['seminar_executions'] = SeminarExecution.all().filter(show_on_index=True)
        context['members'] = Member.all()
        context['testimonials'] = Testimonial.all().order_by('?')
        context['page'] = Index.get_solo()
        return context


class MemberListView(ProtectMixin, AllContextMixin, generic.ListView):
    template_name = 'team.html'
    model = Member

    def get_queryset(self):
        return Member.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seminar_groups'] = SeminarGroup.all()
        context['books'] = Book.all()
        context['page'] = Team.get_solo()
        return context


class ContactView(ProtectMixin, AllContextMixin, generic.FormView):
    template_name = 'contact.html'
    form_class = ContactForm

    def get_success_url(self):
        return reverse('contact') + '?erfolg=True#erfolg'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seminar_groups'] = SeminarGroup.all()
        context['page'] = Contact.get_solo()
        context['success'] = self.request.GET.get('erfolg', default=None)
        return context

    def form_valid(self, form):
        message = form.get_data()
        subject = 'Anfrage über das Kontaktformular auf cocoo.de'
        sender = settings.DEFAULT_FROM_EMAIL
        recipient = settings.DEFAULT_FROM_EMAIL
        send_mail(subject, message, sender, [recipient])
        return super().form_valid(form)


class ImprintView(ProtectMixin, AllContextMixin, generic.TemplateView):
    template_name = 'imprint.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = Imprint.get_solo()
        context['seminar_groups'] = SeminarGroup.all()
        return context


class DataProtectionView(ProtectMixin, AllContextMixin, generic.TemplateView):
    template_name = 'data_protection.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = DataProtection.get_solo()
        context['seminar_groups'] = SeminarGroup.all()
        return context


class SeminarGroupListView(ProtectMixin, AllContextMixin, generic.ListView):
    model = SeminarGroup
    template_name = 'seminargroups.html'

    def get_queryset(self):
        return SeminarGroup.all().prefetch_related(Prefetch('seminar_topics', queryset=SeminarTopic.all()))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seminar_groups'] = SeminarGroup.all()
        context['page'] = Seminars.get_solo()
        return context


class CoachingView(ProtectMixin, AllContextMixin, generic.TemplateView):
    template_name = 'coaching.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = Coaching.get_solo()
        return context


# detail views
class SeminarTopicDetailView(ProtectMixin, AllContextMixin, generic.detail.SingleObjectMixin,
                             generic.FormView):
    model = SeminarTopic
    template_name = 'seminar.html'
    form_class = SeminarRegistrationForm
    queryset = SeminarTopic.all()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['seminartopic'] = self.object
        return kwargs

    def get_success_url(self):
        return reverse('seminartopic_detail', args=[self.object.slug]) + '?erfolg=True#erfolg'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = Seminar.get_solo()
        context['seminar_executions'] = SeminarExecution.all().filter(topic=self.object)
        context['success'] = self.request.GET.get('erfolg', default=None)
        context['meta_title'] = self.object.title
        context['meta_description'] = self.object.short_description
        return context

    def form_valid(self, form):
        message = form.get_data()
        subject = 'Anfrage über das Seminarformular auf cocoo.de'
        sender = settings.DEFAULT_FROM_EMAIL
        recipient = settings.DEFAULT_FROM_EMAIL
        send_mail(subject, message, sender, [recipient])
        return super().form_valid(form)


class MemberDetailView(ProtectMixin, AllContextMixin, generic.DetailView):
    model = Member
    template_name = 'member.html'
    queryset = Member.all().prefetch_related(Prefetch('certificates', queryset=Certification.all()))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = MemberPage.get_solo()
        context['seminar_groups'] = SeminarGroup.all()
        context['meta_title'] = '{} {}'.format(self.object.first_name, self.object.last_name)
        context['meta_description'] = self.object.short_description
        return context

apps/frontend/templates/symbols/pages/index/box.html
<div class="flex pt-2 px-5 pb-5 bg-red-500 rounded-2xl" data-aos="fade-up" data-aos-delay="">
    <div class="pt-2.5 w-full flex flex-col justify-between">
        <a href="{{ href }}" class="block">
            <div class="text-2xl text-center leading-6 font-medium text-white">
                {{ heading }}
            </div>
            <div class="mt-4 text-base text-red-050">
                {{ text }}
            </div>
        </a>
        <div class="mt-3 text-right">
            <a class="{% include 'styles/a.txt' with color='text-red-050 hover:text-white' %}"
               href="{{ href }}">{{ page.intro_leftbutton }}</a>
        </div>
    </div>
</div>

apps/frontend/templates/symbols/pages/index/slide.html
<div :x-transition:enter="transitions('enter')"
     :x-transition:enter-start="transitions('enter-start')"
     :x-transition:enter-end="transitions('enter-end')"
     :x-transition:leave="transitions('leave')"
     :x-transition:leave-start="transitions('leave-start')"
     :x-transition:leave-end="transitions('leave-end')"
     x-show="activeSlide === {{ forloop.counter0 }}"
     class="shadow-lg rounded-2xl min-w-full">
    <div class="overflow-x-hidden overflow-y-sroll">
        <div class="flex flex-col overflow-hidden bg-blue-600 rounded-2xl pt-4 pb-4 pl-4 pr-5">
            <div class="flex-1">
                <p class="text-sm text-blue-050">
                    Vom
                    <time datetime="{{ execution.start_date|date:'Y-m-d' }}">
                        {{ execution.start_date|date:'d.m.Y' }}
                    </time>
                    bis zum
                    <time datetime="{{ execution.end_date|date:'Y-m-d' }}">
                        {{ execution.end_date|date:'d.m.Y' }}
                    </time>
                </p>
                <a href="{% url 'seminartopic_detail' execution.topic.slug %}#anstehende-seminare" class="mt-2 block">
                    <h3 class="text-xl font-semibold text-blue-050">
                        {{ execution.topic.title }}
                    </h3>
                    <p class="mt-3 text-base text-blue-050 max-w-4xl">
                        {{ execution.topic.short_description }}
                    </p>
                </a>
                <div class="mt-3">
                    <div class="text-blue-050 flex items-center space-x-6">
                        <div>
                            <svg class="w-5 h-5 inline text-blue-100 mb-1.5"
                                 xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 20 20"
                                 fill="currentColor">
                                <path fill-rule="evenodd"
                                      d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z"
                                      clip-rule="evenodd"></path>
                            </svg>
                            <div class="inline leading-tight">{{ execution.location|default:execution.get_execution_display }}</div>
                        </div>
                        <div>
                            <svg class="w-5 h-5 inline text-blue-100 mb-1.5" xmlns="http://www.w3.org/2000/svg"
                                 fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                      d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            <div class="inline leading-tight">{{ execution.language }}</div>
                        </div>
                        <div style="margin-left: auto;">
                            <a class="{% include 'styles/a.txt' with color='text-blue-100 hover:text-blue-050' %}"
                               href="{% url 'seminartopic_detail' execution.topic.slug %}">{{ page.intro_leftbutton }}</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-6">
                {% for trainer in execution.members.all %}
                    <div class="flex">
                        <div class="h-16 w-16 md:h-32 md:w-32 mr-3 flex-none">
                            <div class="aspect-h-1 aspect-w-1">
                                <img class="object-cover rounded-full" src="{{ trainer.image.url }}"
                                     alt="{{ trainer.name }}">
                            </div>
                        </div>
                        <div class="">
                            <p class="text-blue-100 leading-tight">Trainer</p>
                            <h4 class="text-blue-050 font-medium mb-2 text-lg">{{ trainer.name }}</h4>
                            <p class="text-sm text-blue-050 max-w-xl">{{ trainer.short_description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

apps/frontend/templates/symbols/pages/index/slider.html
<section class="{% include 'styles/section.txt' %} bg-gray-100 overflow-hidden">
    <div class="{% include 'styles/container.txt' %}">
        <div class="{% include 'styles/padding.txt' %}">
            <div class="pt-32 pb-32">
                <h2 class="{% include 'styles/h2.txt' with color='text-blue-600' %} mb-5 md:text-4xl lg:mb-10"
                    data-aos="fade-up" data-aos-delay="">
                    {{ page.seminars_heading }}
                </h2>
                <div class="" data-aos="fade-up" data-aos-delay="100">
                    <div class="flex relative"
                         x-data="slider()"
                         x-init="setup()">
                        <!-- Previous Arrow -->
                        <div class="flex-col pr-2 text-gray-600 absolute transform left-0 h-full -translate-x-full z-30 hidden md:flex">
                            <button
                                    class="p-2 focus:outline-none h-full"
                                    x-on:click="previous(); auto = false;">
                                <svg class="w-8 h-8 mb-8" xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          stroke-width="2" d="M15 19l-7-7 7-7"></path>
                                    <span class="sr-only">Zurück</span>
                                </svg>
                            </button>
                        </div>
                        <div class="flex flex-col flex-1">
                            <div class="flex flex-row relative">
                                <!-- Slides -->
                                {% for execution in seminar_executions %}
                                    {% include 'symbols/pages/index/slide.html' %}
                                {% endfor %}
                            </div>
                            <!-- Buttons -->
                            <div class="w-full flex items-center justify-center px-4">
                                <template x-for="slide in slidesArray" :key="slide">
                                    <button class="mt-2 py-2 px-1.5 focus:outline-none"
                                            x-on:click="set(slide); auto = false;">
                                        <div class="w-8 h-1.5 overflow-hidden transition-colors duration-200 ease-out"
                                             :class="{
                                                          'bg-blue-500': activeSlide === slide,
                                                          'bg-gray-300': activeSlide !== slide
                                                      }">
                                            <span class="sr-only">Auswählen</span>
                                        </div>
                                    </button>
                                </template>
                            </div>
                        </div>
                        <!-- Next Arrow -->
                        <div class="hidden flex-col h-full pl-2 text-gray-600 z-30 md:flex absolute transform right-0 translate-x-full">
                            <button
                                    class="p-2 h-full focus:outline-none"
                                    x-on:click="next(); auto = false;">
                                <svg class="w-8 h-8 mb-8" xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24"
                                     stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          stroke-width="2" d="M9 5l7 7-7 7"></path>
                                </svg>
                                <span class="sr-only">Weiter</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    window.slider = function () {
        return {
            numberOfSlides: {{ seminar_executions.count }},
            slidesArray: [],
            activeSlide: 0,
            previousSlide: 0,
            auto: true,
            setup() {
                this.slidesArray = Array.from(Array(this.numberOfSlides).keys());
                setTimeout(() => this.autoPlay(), {{ page.seminars_autoplay }});
            },
            autoPlay() {
                if (this.auto) {
                    this.next();
                    setTimeout(() => this.autoPlay(), {{ page.seminars_autoplay }});
                }
            },
            next() {
                if (this.activeSlide === this.slidesArray.length - 1) {
                    this.previousSlide = -1;
                    this.activeSlide = 0;
                } else {
                    this.previousSlide = this.activeSlide;
                    this.activeSlide = this.activeSlide + 1;
                }
            },
            previous() {
                if (this.activeSlide === 0) {
                    this.previousSlide = 999;
                    this.activeSlide = this.slidesArray.length - 1;
                } else {
                    this.previousSlide = this.activeSlide;
                    this.activeSlide = this.activeSlide - 1;
                }
            },
            set(slideNumber) {
                this.previousSlide = this.activeSlide;
                this.activeSlide = slideNumber;
            },
            transitions(state) {
                const rightToLeft = this.activeSlide > this.previousSlide;
                switch (state) {
                    case 'enter':
                        return 'transition duration-1000 transform'
                    case 'enter-start':
                        return `opacity-0 ${rightToLeft ? 'translate-x-full' : '-translate-x-full'}`
                    case 'enter-end':
                        return `opacity-100 ${rightToLeft ? 'translate-x-0' : 'translate-x-0'}`
                    case 'leave':
                        return 'transition duration-1000 transform absolute'
                    case 'leave-start':
                        return `opacity-100 ${rightToLeft ? 'translate-x-0' : 'translate-x-0'}`
                    case 'leave-end':
                        return `opacity-0 ${rightToLeft ? '-translate-x-full' : 'translate-x-full'}`
                }
            }
        }
    }
</script>